### ISSUE TITLE
 Accented characters problem in container

### ISSUE THREAD

**Issue by galaad** [tianon/docker-brew-debian#44] opened 2016-05-25 12:36 UTC
Problem description [here](https://linuxfr.org/forums/linux-debian-ubuntu/posts/comment-passer-les-caracteres-accentues-a-un-shell-bash-dans-docker)

Problem doesn't appear on docker ubuntu:xenial

Solution on ubuntu : http://jaredmarkell.com/docker-and-locales/

**Comment by tianon** [comment] 2016-06-21 00:46
This sounds like a duplicate of #45 -- mind trying the solution linked there?

**Comment by tianon** [comment] 2017-06-07 20:49
This repository is now deprecated in favor of https://github.com/debuerreotype/docker-debian-artifacts, which builds reproducible Debian rootfs tarballs using https://github.com/debuerreotype/debuerreotype. :+1:

**Closed by tianon** 2017-06-07 20:49 UTC
