### ISSUE TITLE
Wheezy Images fails to start

### ISSUE THREAD

**Issue by pluhmen** [tianon/docker-brew-debian#59] opened 2017-01-02 13:01 UTC
I've freshly pulled wheezy image from your image repo, when I'm starting ```docker run -ti debian:wheezy``` the container docker fails with.

```
level=warning msg="failed to close stdin: rpc error: code = 2 desc = containerd: container not found"
```

Debug-Output

```
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.876017162+01:00" level=debug msg="Calling POST /v1.24/containers/create"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.876445707+01:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"debian:wheezy\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":true,\"StdinOnce\":true,\"Tty\":true,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.903736699+01:00" level=debug msg="container mounted via layerStore: /var/lib/docker/overlay/fe963f214b601d1a00911be756de23e71939a9bea61aec0370542c9174dbe87a/merged"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.926554286+01:00" level=debug msg="Calling POST /v1.24/containers/ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468/attach?stderr=1&stdin=1&stdout=1&stream=1"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.926773285+01:00" level=debug msg="attach: stdin: begin"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.926864095+01:00" level=debug msg="attach: stdout: begin"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.926942689+01:00" level=debug msg="attach: stderr: begin"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.927482535+01:00" level=debug msg="Calling POST /v1.24/containers/ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468/start"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.928502479+01:00" level=debug msg="container mounted via layerStore: /var/lib/docker/overlay/fe963f214b601d1a00911be756de23e71939a9bea61aec0370542c9174dbe87a/merged"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.928761036+01:00" level=debug msg="Assigning addresses for endpoint distracted_noyce's interface on network bridge"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.928794512+01:00" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Jan 02 13:55:22 microbee dockerd[2661]: time="2017-01-02T13:55:22.930782808+01:00" level=debug msg="Assigning addresses for endpoint distracted_noyce's interface on network bridge"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.049214946+01:00" level=debug msg="Programming external connectivity on endpoint distracted_noyce (52f52ce0004ebba10cd9224b386b484ceed076eea1f7b01f926fd76fbe956748)"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.173322020+01:00" level=debug msg="sandbox set key processing took 64.241178ms for container ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.216791829+01:00" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc820830090)}"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.219538805+01:00" level=debug msg="libcontainerd: event unhandled: type:\"start-container\" id:\"ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468\" timestamp:<seconds:1483361723 nanos:216344107 > "
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.220079642+01:00" level=debug msg="Calling POST /v1.24/containers/ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468/resize?h=24&w=95"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.264183194+01:00" level=debug msg="containerd: process exited" id=ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468 pid=init status=139 systemPid=2800
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.271880362+01:00" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468\", Status:0x8b, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc8208307b0)}"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.272230766+01:00" level=debug msg="attach: stdout: end"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.272284362+01:00" level=debug msg="attach: stdin: end"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.272324427+01:00" level=debug msg="attach: stderr: end"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.272412292+01:00" level=debug msg="Closing buffered stdin pipe"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.272601195+01:00" level=debug msg="Revoking external connectivity on endpoint distracted_noyce (52f52ce0004ebba10cd9224b386b484ceed076eea1f7b01f926fd76fbe956748)"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.273881514+01:00" level=debug msg="Calling GET /v1.24/containers/ac80e2bd926fff579f11d2886f9dee20ef9fed8c4fcffd0a428f99fd1ccad468/json"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.274772474+01:00" level=warning msg="failed to close stdin: rpc error: code = 2 desc = containerd: container not found"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.367564269+01:00" level=debug msg="Releasing addresses for endpoint distracted_noyce's interface on network bridge"
Jan 02 13:55:23 microbee dockerd[2661]: time="2017-01-02T13:55:23.367619189+01:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1)"
```

docker info:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.12.5
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.8.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.819 GiB
Name: microbee
ID: BZT5:V5BI:L33F:JIJE:LYNB:AJNP:3Q5Z:27QM:MMOI:QIZC:MYGW:W3HV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2017-01-02T13:59:13.339915963+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

On the same system/setup jessie works fine...

**Comment by tianon** [comment] 2017-01-02 16:55
Since it's only affecting Wheezy, I'm inclined to think this is likely a duplicate of #55 -- can you test adding `vsyscall=emulate` to your GRUB/kernel boot parameters and try again?

**Comment by pluhmen** [comment] 2017-01-05 19:47
@tianon The kernel parameter works! https://github.com/pluhmen/docker-sogo-build-wheezy

**Comment by tianon** [comment] 2017-01-05 20:25
Excellent, thanks for confirming! :+1:

**Closed by tianon** 2017-01-05 20:25 UTC

**Comment by pluhmen** [comment] 2017-01-05 20:47
@tianon No problem.
